[project]
name = "minidl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "sphinx>=8.2.3",
]
